CREATE TABLE PROD (ID INTEGER, PRODUCTO TE¨XT, PRECIO INTEGER);

SELECT * FROM PROD;

INSERT INTO PROD VALUES (1, "IMPRESORA", 50);

SELECT * FROM PROD;

INSERT INTO PROD VALUES (1, "RATON", 10);

SELECT * FROM PROD;