CREATE TABLE PERSONAS2 (ID INTEGER PRIMARY KEY, NOMBRE TEXT, APELLIDO TEXT, DEP INTEGER, 
FOREIGN KEY ("DEP") REFERENCES "DEPARTAMENTOS" ("DEP"));

SELECT * FROM DEPARTAMENTOS LIMIT 10;

INSERT INTO PERSONAS2 VALUES (1, "KENDAL", "VILLACORTA", 2);
SELECT * FROM PERSONAS2;

INSERT INTO PERSONAS2 VALUES (2, "ERIKA", "PACHECO", 3);
SELECT * FROM PERSONAS2;