SELECT * FROM PERSONAS ORDER BY NOMBRE LIMIT 10;

INSERT INTO PERSONAS VALUES (5, "VICTOR", "VILLACORTA", "PLASENCIA", 45139145, 26, 1, NULL);

UPDATE PERSONAS SET EDAD = 31 WHERE APELLIDO1 LIKE "%VILLA%";

DELETE FROM PERSONAS WHERE NOMBRE = "VICTOR";