CREATE TABLE PROD3 (ID INTEGER PRIMARY KEY, PRODUCTO TEXT, PRECIO INTEGER);
INSERT INTO PROD3 VALUES (1, "IMPRESORA", 50);
SELECT * FROM PROD3;


INSERT INTO PROD3 VALUES (2, "MONITOR", 50);
SELECT * FROM PROD3;