CREATE TABLE PROD4 (ID INTEGER PRIMARY KEY AUTOINCREMENT, PRODUCTO TEXT, PRECIO INTEGER);
INSERT INTO PROD4 VALUES (1, "IMPRESORA", 50);
SELECT * FROM PROD4;


INSERT INTO PROD4 VALUES (2, "MONITOR", 50);
SELECT * FROM PROD4;